apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: monitor
  labels:
    release: prometheus
spec:
  groups:
  - name: test-group
    rules:
    - alert: TestAlert

      expr: up{job="prometheus-operator"} == 1
      for: 10s
      labels:
        severity: test
      annotations:
        summary: "This is a test alert"
        description: "If you see this message in Discord, the entire alerting pipeline is working correctly! 🎉"